# Generated by Django 5.2.4 on 2025-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
