# Generated by Django 5.2.4 on 2025-07-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_jobapplication_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='match_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
